version: '2.1'
services:
    beaconService:
        build: ./beaconService
        privileged: true
        restart: always
        network_mode: host
    dashboard:
        build: ./dashboard
        ports: 
            - 80:80
        privileged: true
        restart: "no"
        network_mode: host
    